### ISSUE TITLE
Create tests which verify the full inputs

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-wannier90#10]
Currently, inputs such as e.g. the projections could be malformed, since the test run doesn't actually depend on it being correct.

Maybe the test from the QE - Wannier90 plugin can be used?

**Comment by greschd** [comment]
@giovannipizzi I think this is partially addressed with the recent changes. Maybe we should close this, and if there are specific things we want to test open separate issues?

**Comment by giovannipizzi** [comment]
Yes.
This is fixed by a number of recent PRs including #85, #87 and a number of earlier ones adding tests.
