### ISSUE TITLE
Define exit codes that should invalidate the cache

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-wannier90#102]
By default, AiiDA will consider all terminated calculations as valid cache, regardless of their exit code. This makes sense for calculations that failed for a "deterministic reason" (e.g., malformed input), but not for calculations that fail due to intermittent issues on the cluster.

To handle this, the `invalidates_cache` keyword can be set on exit codes (since AiiDA 1.1, https://github.com/aiidateam/aiida-core/pull/3637) to indicate that calculations with that exit code should not be used as cache sources. It's documented [here](https://aiida.readthedocs.io/projects/aiida-core/en/v1.2.0/developer_guide/core/caching.html#controlling-caching), don't think it made it to the new documentation yet...

I think `aiida-wannier90` should use this at least for the `2xx` range errors.

@giovannipizzi do you think it's important to implement this in a `1.0` - compatible way, or should we go to `1.1+` from the next release on? I couldn't find the list of which AiiDA versions are supported until when, but I assume the main reason to stay on `1.0` would be Python2 compatibility - which we've dropped here anyway.

**Comment by giovannipizzi** [comment]
Just to be sure, the current version is 1.0 compatible, right?
I think it's ok to move on to a new version that is only 1.1+ (I would be OK even with 1.3+) compatible, and py3 only.
If you want to work on a new branch about this, please go ahead! Maybe @qiaojunfeng can help at least reviewing the PRs?

**Comment by greschd** [comment]
> Just to be sure, the current version is 1.0 compatible, right?

Yes

> I think it's ok to move on to a new version that is only 1.1+ (I would be OK even with 1.3+) compatible, 

Ok, in that case the change should be really simple - unless we want to define ranges of exit codes that do it automagically, but I think that's not necessary yet.
There's not really any need to go 1.3+, since AFAIK there are no features we need here that aren't available in 1.1+. But yeah, in general I think we should just use the latest features here, and deprecate support for older AiiDA versions when that happens.

> and py3 only.

That was already done in https://github.com/aiidateam/aiida-wannier90/pull/94, but no released yet.

> If you want to work on a new branch about this, please go ahead! Maybe @qiaojunfeng can help at least reviewing the PRs?
