### ISSUE TITLE
name of "retrieve_hoppings"

### ISSUE THREAD

**Issue by AntimoMarrazzo** [aiidateam/aiida-wannier90#14]
What about 'retrieve_tbmodel' or anything else? the idea you retrieve the tight binding model...

**Comment by greschd** [comment]
How about ``retrieve_tb``, to be consistent with the Wannier90 option name ``write_tb``?

**Comment by greschd** [comment]
Just to be clear: The option should retrieve not only the ``_hr.dat`` file, but also the other files generated with ``write_tb``, correct? Otherwise I'd be in favor of keeping the name, or changing it to ``retrieve_hr``. I think it makes sense to be consistent with the Wannier90 ``write_*`` options.

**Comment by AntimoMarrazzo** [comment]
Actually seedname_tb.dat is a brand new output file. So maybe we change it retrieve_hr and later implement write_tb that retrieves only _tb.dat. In other words, I agree we need to be consistent with Wannier90.

**Comment by greschd** [comment]
Yes, that makes sense :+1:

**Comment by greschd** [comment]
Looking at this again, I wonder why we need an option to disable retrieving these files. Wannier90 already has options to configure if the files are _written_, so if they are written I think they should also be retrieved.

That is, I think all output files which aren't parsed specifically should just be put in the ``retrieve_list`` unconditionally at https://github.com/aiidateam/aiida-wannier90/blob/develop/aiida_wannier90/calculations.py#L328.

Related issue: #69.
Tagging @giovannipizzi for comment.

**Comment by AntimoMarrazzo** [comment]
I see your logic, indeed one could just disable the writing of the Hamiltonian...
Originally, we introduced that flag because the Hamiltonian is a relatively heavy files so there are a number of cases where you just don't want to store in the repository.
Now I am thinking at possible use cases where the Hamiltonian is passed to another code (e.g. tbmodels, postw90) for postprocessing: there you may avoid to store the Hamiltonian in the repo and, at the same, you need to write it on the remote directory.
Does it make sense?
Anyhow, we can also set the default to be "parse all you find" and leave an optional flag to disable parsing of selected files...

**Comment by greschd** [comment]
Hmm yeah that could be a use case for not retrieving them. In the end this only works if the plugin for the using code also supports remote input.. which in the case of ``aiida-tbmodels`` I haven't implemented 😅
But I agree that we want to at least enable this from the side of ``aiida-wannier90``, so maybe the question is just if it should default to retrieving or not retrieving.

**Comment by giovannipizzi** [comment]
Fixed in #79 - now everything known is retrieved (but it is possible to say in the `settings` what you don't want), since anyway if the file is being generated, it's because it's asked for in the input of Wannier90
