### ISSUE TITLE
random projections as default

### ISSUE THREAD

**Issue by AntimoMarrazzo** [aiidateam/aiida-wannier90#15]
Currently if no projections are specified the plugin set them to random.
Do we want to keep this as default? Or is it better to explicitly ask users to write 'random' as a list?

**Comment by greschd** [comment]
I think we want to keep that, since that's also what Wannier90 does IIRC.

**Comment by giovannipizzi** [comment]
If Wannier does it, then is it really needed to add 'random'? I think that in this case it is better to leave the block empty, and not add a line containing the string 'random'?

**Comment by greschd** [comment]
True, we could just allow the input to not be there.

**Comment by giovannipizzi** [comment]
Ok, we're implementing this then. We're also adding the possibility to specify the 'random' keyword for a partial list of projections, when passed as a OrbitalData object (when passing a list it's trivial, one just needs to put 'random' as the first element of the string).

**Comment by greschd** [comment]
Seems this no longer work in the current ``develop`` branch, because ``projections`` is a required input. Maybe just setting ``required=False`` fixes this, but it needs testing.
