### ISSUE TITLE
Add documentation to the plugin

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#17]

**Comment by greschd** [comment]
We could extend the AiiDA Sphinx extension, to add a directive for documenting calculation classes.

**Comment by giovannipizzi** [comment]
Good idea!
I've no experience with that, but very happy to contribute if there is some example.

**Comment by giovannipizzi** [comment]
Another comment (also for @AntimoMarrazzo and @greschd ) I think it's good that if we do `import aiida_wannier90`) this does not crash if we have not loaded the dbenv.
I've moved imports inside functions so at least in __init__ there's no place that requires a dbenv (hopefully in the future we'll improve this also on the AiiDA side).
Anyway if this gets broken, I think also the docs will stop compiling.

**Comment by greschd** [comment]
@giovannipizzi Maybe we can add a test for not requiring the dbenv on import -- can you make a separate issue for that?

**Comment by giovannipizzi** [comment]
I'm closing this as I think we can fix it by fixing #7
