### ISSUE TITLE
exclude_band

### ISSUE THREAD

**Issue by AntimoMarrazzo** [aiidateam/aiida-wannier90#2]
exclude bands does not work for len(exclude_bands)>~10, because the plugin converts it into a range and it is easy to exceed the maximum line length. We should do something more clever...

**Comment by greschd** [comment]
Ok, I think it shouldn't be too hard to make some logic that groups the bands into contiguous blocks and puts a ``-`` in between.

**Comment by greschd** [comment]
See https://github.com/aiidateam/aiida-wannier90/blob/master/aiida_wannier90/calculations/_util.py.
