### ISSUE TITLE
kpoint_path format

### ISSUE THREAD

**Issue by AntimoMarrazzo** [aiidateam/aiida-wannier90#20]
Regarding the kpoint_path options in Wannier90 , do you use it by giving in input a KpointsData? The plugin now uses that just to get the special points, so with @giovannipizzi we were thinking to allow as input a ParameterData where you just specify a list with labels and coordinates of high-simmetry points.

**Comment by greschd** [comment]
I'm not using the ``kpoint_path`` at all right now, because I do some additional post-processing before calculating the bandstructure.

How would that ``ParameterData`` be different (in terms of what you have to specify) from just creating a ``KpointsData`` with ``set_kpoints_path``? The only reason I can see against allowing this is that it might complicate things to add another way of specifying k-points over the ones which are in ``aiida-core``.

**Comment by giovannipizzi** [comment]
I'm thinking to commit the change to allow something like
```python
u'path': [[u'GAMMA', u'X'],
    [u'X', u'U'],
    [u'K', u'GAMMA'],
    [u'GAMMA', u'L'],
    [u'L', u'W'],
    [u'W', u'X']],
    u'point_coords': {u'GAMMA': [0.0, 0.0, 0.0],
    u'K': [0.375, 0.375, 0.75],
    u'L': [0.5, 0.5, 0.5],
    u'U': [0.625, 0.25, 0.625],
    u'W': [0.5, 0.25, 0.75],
    u'W_2': [0.75, 0.25, 0.5],
    u'X': [0.5, 0.0, 0.5]}
```
that is in the end just the two values returned but `set_kpoints_path`.
This function, btw, is quite 'broken' (at least if not used properly) and I would like at some point to remove it from AiiDA and have instead seekpath as the default.

The reason why we believe this is better is also that we are giving a complex kpointsdata to have, in the end, just a list of endpoints.

If it's ok, I will for now allow both the old way with a KpointsData and with a ParameterData, and later we can deprecate/remove the KpointsData option (maybe actually we can deprecate it already now).

**Comment by greschd** [comment]
I think it's ok to deprecate it already now. Can you change the test accordingly? Actually, can you run the tests locally on your machines? Now that the ``.aiida`` folder lookup is in ``aiida-core``, you should be able to just create a ``config.yml`` (you can copy from ``config_example.yml``) and change the path to Wannier90 and your tmp directory.

**Comment by greschd** [comment]
Might also be a good idea to add a Travis build -- that shouldn't be that hard, we just need to figure out how best to build Wannier90 on Travis.

**Comment by greschd** [comment]
Or we can replace ``aiida-pytest`` with Rico's test fixtures and just do tests that don't require running Wannier90 itself, or the daemon.

**Comment by giovannipizzi** [comment]
I changed the type and adapted the tests.

**Comment by giovannipizzi** [comment]
I added the docs. I move the discussion of the tests to a different issue

**Comment by giovannipizzi** [comment]
Actually, there's already an issue, #18
