### ISSUE TITLE
Update how 'create_gaas_calc' is handled 

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-wannier90#27]
create_gaas_calc is managed under @pytest.fixture, either change how this is handled or update the associated tests

**Comment by giovannipizzi** [comment]
@greschd @DanielMarchand I'm not sure I understand the details of this issue - is still still an issue (and if so can this be explained a bit in more detail) or can we close this?

**Comment by greschd** [comment]
I think we can close it. @DanielMarchand please re-open if you disagree.
