### ISSUE TITLE
Move .win file writer to a separate function in _utils.py, and test spinor projections

### ISSUE THREAD

**Issue by AntimoMarrazzo** [aiidateam/aiida-wannier90#3]
Provide option to give raw projections

**Comment by greschd** [comment]
TODO: 
- [ ] Handle difference between spin / no-spin projections
- [ ] Write tests

**Comment by greschd** [comment]
@giovannipizzi this is also fixed by #85, right?

**Comment by giovannipizzi** [comment]
Not really, in #85 I didn't write tests for the spin case.
Just did it in #87. I'm also going to rename now this issue.
