### ISSUE TITLE
Cleanup/Modernize the examples directory

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-wannier90#30]
The examples directory is confusing, and possibly filled with obsolete methods. The 'workflows' directory is not even a workflow. The contents of these tests should be checked, merged, and made generic.

**Comment by DanielMarchand** [comment]
This task would also include making sure the examples can be run at least once, easily, and from two separate computers (ideally from two separate people)

**Comment by giovannipizzi** [comment]
@normarivano  has been working on this. Some preliminary work has been committed in 66ca63d2bb560d35b52. The `workflows` folder needs to be still checked, and the README reviewed

**Comment by greschd** [comment]
Just to make sure, did we check that the https://github.com/aiidateam/aiida-wannier90/blob/develop/examples/example01/wannier_gaas.py is fixed also?
