### ISSUE TITLE
Address the issues mentioned by "NOTE" in calculations.py

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-wannier90#31]
In aiida_wannier/calculations.py there are multiple spots where I was confused by the update process,  and are marked with "NOTE" these should be addressed. (This should be done after/in-conjunction with correcting the unit tests)

**Comment by giovannipizzi** [comment]
@normarivano could you please check if any `NOTE` is still around, remove them from the code, add them as separate issues and then close this one (mentioning the issues that you have opened, if needed)? Thanks!

**Comment by giovannipizzi** [comment]
I'm closing this as the last notes will be fixed in #76
