### ISSUE TITLE
Pymatgen's "monty" dependency seems to break Python 2 compatibility

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-wannier90#39]
Since the dependency to ``monty`` is not pinned on the older pymatgen version, the recent (Sept. 30th) release of ``monty==3.0.0`` broke our build for Python 2, see e.g. [this travis build](https://travis-ci.org/aiidateam/aiida-wannier90/jobs/605554168?utm_medium=notification&utm_source=github_status).

Options are:
- Explicitly pin the monty version (the obvious solution)
- Drop Python 2 support (will do that eventually anyway)

@giovannipizzi @normarivano, opinions?

**Comment by giovannipizzi** [comment]
I would keep python 2 support at least for one release; as soon as we release it, we can drop it.
I already committed and closed the issue, but we can reopen if the fix isn't enough
