### ISSUE TITLE
Enable branch protections

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-wannier90#40]
@giovannipizzi @normarivano we probably shouldn't push directly to ``develop``, and try to keep the tests we have running. I don't have the necessary permissions, @giovannipizzi can you enable the proper branch protection rules?

**Comment by giovannipizzi** [comment]
Agreed, this wasn't done on purpose, sorry about that.
I'll now protect the branch (I will just check if we can quickly fix the tests first.

**Comment by giovannipizzi** [comment]
I protected the branch.
I didn't set a required test pass because tests are still failing, and I'm not sure why yet.
Maybe @greschd you could help us out for this? In the meantime we'll probably make another PR to clean up the previous commits.

**Comment by giovannipizzi** [comment]
Now that #49 is merged I've activated the requirement that tests need to pass

**Comment by greschd** [comment]
Sweet 👍
