### ISSUE TITLE
Fix failing tests in develop

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#45]
In this way, we can set a branch protection connected to Travis.

**Comment by giovannipizzi** [comment]
@greschd would you mind looking into it? Let us know if you need help.

**Comment by greschd** [comment]
Ah wow.. in ``aiida-pytest`` there is an ``__all__`` that contained a ``unicode`` in py2 because of the ``from __future__ import unicode_literals``. That fails, because it's only allowed to be ``str``.

I'll fix that and release ``aiida-pytest==0.1.0a6`` shortly.
