### ISSUE TITLE
Change the .travis.yml to use the correct dependencies

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#47]
We depend on AiiDA develop in the `travis.yml` file. Now that AiiDA 1.0 is released, we should probably pin instead to aiida-core>=1,<2? Or even more specifically, let this be managed by the pip dependencies?

Same question for aiida_pytest - @greschd what do you suggest to do?

**Comment by greschd** [comment]
Yeah, the simple pip install should work now - no need to explicitly install aiida-core and aiida-pytest.

**Comment by greschd** [comment]
I'll get that fixed together with the general issues with tests on travis.

**Comment by giovannipizzi** [comment]
Thanks!
