### ISSUE TITLE
Should `.pytest_cache/v/test_win_writer` be in the repo?

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#50]
There are two files in `.pytest_cache/v/test_win_writer`. From the name I'm guessing these were committed by mistake? Also because `.pytest_cache` is in the .gitignore.

If this is the case, can these be removed?

**Comment by greschd** [comment]
Yes, this is an ugly way of having reference data to compare against (see the ``compare_data`` fixture).

The better way of doing this would be ``pytest-regressions`` or ``pytest-datadir`` (see also my recent e-mail). So for now this needs to be there, but should be migrated away from.

**Comment by greschd** [comment]
Closing this in favor of #53 - simply removing the cache directory now will break tests, it needs to be migrated properly.
