### ISSUE TITLE
status of plugin 

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-wannier90#62]
I'm looking to make a new Quantum Mobile release and Wannier90 is one of the codes, so it should be shipped together with an AiiDA plugin.
I see that the last release of the wannier90 plugin is from 2018. 
Does the develop branch work with AiiDA 1?
If yes, should there perhaps be a new release?

mentioning @giovannipizzi

**Comment by greschd** [comment]
I don't think we're quite ready for a release yet -- the ``develop`` branch kind-of works with 1.0, but only one "happy path" is currently tested. Documentation and examples are also still lagging behind.

Most importantly, I think we need to go through the _interface_ and see if there are things that need to be changed / renamed.

What's the timeline for the Quantum Mobile release?

**Comment by greschd** [comment]
See also the milestone: https://github.com/aiidateam/aiida-wannier90/milestone/1

**Comment by greschd** [comment]
If you absolutely need a release before we're all the way done, we can probably make a pre-release.

**Comment by giovannipizzi** [comment]
Indeed, I agree with @greschd 
Maybe, since at least one code path is working, we could start releasing a alpha1 to include in the Quantum Mobile (at least people can try it out), even if as @greschd we are still in the process of possibly changing the keys of the output of the parser for better consistency - and I would release a beta after this, aiming for an actual release soon after, when the milestone 1 is done.

**Comment by giovannipizzi** [comment]
For the record - we're aiming at releasing this soon, so it can be used for the Wannier90 school in late March - where we want to use the Quantum Mobile

**Comment by giovannipizzi** [comment]
I think that as soon as #82 is fixed, we can already do a rc1, so we can prepare a Quantum Mobile with it - and then we can do #7 (documentation) next week (@normarivano was willing to help), before the final release (of course if someone e.g. @greschd wants to work on it, great - I think it's mostly making sure that the docs are up to date with the code).

**Comment by greschd** [comment]
Agree that the code is ready for a release candidate.

I won't get around to writing documentation next week, but if there are technical issues / questions in building it feel free to ping me @normarivano.

**Comment by giovannipizzi** [comment]
Documentation has been fixed by @normarivano and myself in #7 
Release 2.0 just done and also on [pypi](https://pypi.org/project/aiida-wannier90/2.0.0/
)

I am therefore alerting @ltalirz so he can include it in the Quantum Mobile, and I am closing this issue!

**Comment by greschd** [comment]
Thanks a lot @normarivano @qiaojunfeng @giovannipizzi!
