### ISSUE TITLE
Incorrect projection when radial_nodes is None but diffusivity is not

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-wannier90#9]
``zona`` will take the place of ``radial``, which gives means the wrong projection is used

**Comment by greschd** [comment]
I fixed the issue, but it still needs testing.

**Comment by giovannipizzi** [comment]
Hi @greschd, just to know about this issue: is this issue now fixed in the code, or not yet?

We are planning a beta release hopefully in 2 weeks, to be ready for the Wannier workshop in late March, so we know if we need to check this or it's already fixed. Thanks!

**Comment by greschd** [comment]
I kind of forgot what this issue was exactly, but digging through the commit history I think this change fixed it: https://github.com/aiidateam/aiida-wannier90/commit/0b5d8fe7b8cf8402f5a63a5cd91386f0fcd06f94

So it seems this is indeed fixed in the code, but would still be great to test.

**Comment by greschd** [comment]
> We are planning a beta release hopefully in 2 weeks

let's finish things up at the hackathon?
